spring:
  application:
    name: activityservice
  datasource:
   url: jdbc:postgresql://localhost:5432/fitness_user_db
  username: postgres
  password: Sujal
  jpa:
        hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect

